//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.CustomerLadgers = new HashSet<CustomerLadger>();
        }
    
        public int AccountId { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<bool> Active { get; set; }
        public int EntityId { get; set; }
        public int EntityTypeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLadger> CustomerLadgers { get; set; }
    }
}
