//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressInfo
    {
        public int AdressId { get; set; }
        public string AddressInfo1 { get; set; }
        public string AddressInfo2 { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityId { get; set; }
        public string LocationName { get; set; }
        public int Pincode { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public int Mobile { get; set; }
        public int EntityTypeId { get; set; }
        public int AddressTypeId { get; set; }
        public int ENtityId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
