//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AddressInfo
    {
        public int AdressId { get; set; }
        [Required]
        [Display(Name = "Address Line1")]
        public string AddressInfo1 { get; set; }
        [Display(Name = "Address Line2")]
        public string AddressInfo2 { get; set; }
        [Display(Name = "State")]
        [Required(ErrorMessage ="Please Select State Name")]
        public Nullable<int> StateID { get; set; }
        [Display(Name = "City")]
        public Nullable<int> CityId { get; set; }
        public string LocationName { get; set; }
        [DataType(DataType.Text)]
        public int Pincode { get; set; }
        [DataType(DataType.Text)]
        public Nullable<int> PhoneNumber { get; set; }
        [DataType(DataType.Text)]
        public int Mobile { get; set; }
        public int EntityTypeId { get; set; }
        public int AddressTypeId { get; set; }
        public int ENtityId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
