//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTrasaction
    {
        public int CustomerTrnasactionId { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> TransactionStatus { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> TransactioSource { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Porduct Porduct { get; set; }
    }
}
