//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPasswordDetail
    {
        public int MemberUserId { get; set; }
        public int TestUserId { get; set; }
        public string password { get; set; }
        public int PasswordType { get; set; }
        public Nullable<System.DateTime> PasswordLockedDate { get; set; }
        public Nullable<bool> IsActiveUser { get; set; }
        public Nullable<bool> IsLockedUsers { get; set; }
    
        public virtual Test_Users Test_Users { get; set; }
    }
}
