//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDatabaseEntities : DbContext
    {
        public TestDatabaseEntities()
            : base("name=TestDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerLadger> CustomerLadgers { get; set; }
        public virtual DbSet<CustomerLadgerTrail> CustomerLadgerTrails { get; set; }
        public virtual DbSet<CustomerTrasaction> CustomerTrasactions { get; set; }
        public virtual DbSet<MemberPasswordDetail> MemberPasswordDetails { get; set; }
        public virtual DbSet<Merchant> Merchants { get; set; }
        public virtual DbSet<Porduct> Porducts { get; set; }
        public virtual DbSet<Test_Users> Test_Users { get; set; }
        public virtual DbSet<ValueType> ValueTypes { get; set; }
        public virtual DbSet<ValueTypeGroupd> ValueTypeGroupds { get; set; }
        public virtual DbSet<PasswordChangeLast> PasswordChangeLasts { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<DepartmentTeacher> DepartmentTeachers { get; set; }
        public virtual DbSet<AddressInfo> AddressInfoes { get; set; }
    }
}
