//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueType
    {
        public int ValuetypeId { get; set; }
        public int ValueTypeGroupId { get; set; }
        public string ValueTyepName { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ValueTypeGroupd ValueTypeGroupd { get; set; }
    }
}
